export const GET_SAVED_LIST_REQUEST = "GET_SAVED_LIST_REQUEST";
export const GET_SAVED_LIST_SUCCESS = "GET_SAVED_LIST_SUCCESS";
export const GET_SAVED_LIST_FAIL = "GET_SAVED_LIST_FAIL";


export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAIL";

export const REMOVE_CART_REQUEST = "REMOVE_CART_REQUEST";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_FAIL = "REMOVE_CART_FAIL";

