export const SIDEBAR_TOGGLER = "SIDEBAR_TOGGLER";
export const ADD_CART_POPUP_TOGGLER = "ADD_CART_POPUP_TOGGLER";
export const NOTIFICATION_TOGGLER = "NOTIFICATION_TOGGLER";
export const PROFILE_TOGGLER = "PROFILE_TOGGLER"